source 'https://github.com/CocoaPods/Specs.git'


use_frameworks!

platform :ios, '12.0'

target 'VoilaCam_Example' do
  pod 'VoilaCam', :path => '../'

  target 'VoilaCam_Tests' do
    inherit! :search_paths

    
  end
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end

